version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off
after_build:
    - 7z a -tzip BackVueDownloader-v$(appveyor_build_version).zip %APPVEYOR_BUILD_FOLDER%\bin\Release\netcoreapp1.0\win10-x64
artifacts:  
- path: BackVueDownloader-v$(appveyor_build_version).zip
  name: BackVueDownloader
deploy:
  release: BackVueDownloader-v$(appveyor_build_version)
  description: 'BlackVueDownloader Release v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: +L7awVOpkoS9AFH2iw1R84aEas7eGSFoR1MmKz285Svi8M2H3cSZ8h47bG9NRenw
  artifact: Binaries
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
